from models.shuffleNet.shuffleNetV1 import ShuffleNetV1_0_5x
from models.shuffleNet.shuffleNetV1 import ShuffleNetV1_1_0x
from models.shuffleNet.shuffleNetV1 import ShuffleNetV1_1_5x
from models.shuffleNet.shuffleNetV1 import ShuffleNetV1_2_0x

from models.shuffleNet.shuffleNetV2 import ShuffleNetV2_0_5x
from models.shuffleNet.shuffleNetV2 import ShuffleNetV2_1_0x
from models.shuffleNet.shuffleNetV2 import ShuffleNetV2_1_5x
from models.shuffleNet.shuffleNetV2 import ShuffleNetV2_2_0x